Controllers/CakeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JoysCakeShop.Models;
using JoysCakeShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace JoysCakeShop.Controllers
{
    public class CakeController : Controller
    {
        private readonly ICakeRepository _CakeRepository;
        private readonly ICategoryRepository _CategoryRepository;

        public CakeController(ICakeRepository cakerepo, ICategoryRepository categoryrepo)
        {
            _CakeRepository = cakerepo;
            _CategoryRepository = categoryrepo;
        }

        public ViewResult List()
        {
            CakesListViewModel cakeslistviewmodel = new CakesListViewModel();
            cakeslistviewmodel.Cakes = _CakeRepository.AllCakes;
            cakeslistviewmodel.CurrentCategory = "Our Finest Collection of Cakes curated to your needs!";
            return View(cakeslistviewmodel);
        }

        public IActionResult Details(int id)
        {
            CakesDetailsViewModel cakesdetailsviewmodel = new CakesDetailsViewModel();
            var cake = _CakeRepository.getCakebyId(id);

            cakesdetailsviewmodel.CakeId = cake.CakeId;
            cakesdetailsviewmodel.Name = cake.Name;
            cakesdetailsviewmodel.Description = cake.Description;
            cakesdetailsviewmodel.Price = cake.Price;
            cakesdetailsviewmodel.ImageUrl = cake.ImageUrl;
            
            if (cakesdetailsviewmodel == null) 
                return NotFound();
            else
            {
                return View(cakesdetailsviewmodel);
            }


        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace JoysCakeShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_CakeCard.cshtml
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Cake"
                   asp-action="Details"
                   asp-route-id="@Model.CakeId">@Model.Name</a>
            </h3>
            <p>@Model.Description</p>
        </div>

        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-cakeId="@Model.CakeId">Add to cart</a>
            </p>
        </div>

    </div>
</div>

Views/Shared/_Carousal.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        @await Component.InvokeAsync("CategoryMenu")         <!-- Invoking the Category menu view component -->
                        @await Component.InvokeAsync("ShoppingCartSummary")  <!-- Invoking the shopping cart view component -->
                        <li><a asp-controller="Contact" asp-action="Index">Order Now</a></li>
                        <partial name="_LoginPartial"/>

                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <a href="/"><img class="img-responsive" alt="Joys Cake Shop'" src="~/Images/joys.png" /></a>
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
     </div>
     @RenderSection("Scripts",required: false)
</body>
</html>